"""First

Revision ID: cd7b73c46856
Revises: f01254b2be7d
Create Date: 2023-10-22 20:15:48.567437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7b73c46856'
down_revision = 'f01254b2be7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
